"""replace_status_with_type_in_cow

Revision ID: 1ae40440dbf4
Revises: 
Create Date: 2026-08-01 18:01:36.754600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae40440dbf4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cows', sa.Column('type', sa.String(), nullable=True))
    op.drop_column('cows', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cows', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('cows', 'type')
    # ### end Alembic commands ###
