"""Add assigned_to_id to daily_distribution

Revision ID: 86cd57f0af58
Revises: 9633bff01cde
Create Date: 2026-08-02 08:28:44.890753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86cd57f0af58'
down_revision: Union[str, None] = '9633bff01cde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_distribution', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'daily_distribution', 'members', ['assigned_to_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'daily_distribution', type_='foreignkey')
    op.drop_column('daily_distribution', 'assigned_to_id')
    # ### end Alembic commands ###
