"""split gowal milk

Revision ID: 9633bff01cde
Revises: 26f4267a047f
Create Date: 2026-08-01 23:16:53.522941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9633bff01cde'
down_revision: Union[str, None] = '26f4267a047f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('members_member_number_key'), 'members', type_='unique')
    op.create_index(op.f('ix_members_member_number'), 'members', ['member_number'], unique=True)
    op.add_column('settings', sa.Column('morning_gowal_milk', sa.Float(), nullable=True))
    op.add_column('settings', sa.Column('evening_gowal_milk', sa.Float(), nullable=True))
    op.drop_column('settings', 'gowal_milk')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('gowal_milk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('settings', 'evening_gowal_milk')
    op.drop_column('settings', 'morning_gowal_milk')
    op.drop_index(op.f('ix_members_member_number'), table_name='members')
    op.create_unique_constraint(op.f('members_member_number_key'), 'members', ['member_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
